### ISSUE TITLE
TypeError: invalid destination position for blit

### ISSUE THREAD

**Issue by PeterPan1994** [70RMUND/Tormund-BFV-Radar#1]
Sometimes while using, the radar will closed and in CMD the following message appears: "TypeError: invalid destination position for blit". It's not possible to re-start the radar without leaving the currently round and to login again to the server.

Also sometimes, the Radar will not run from the beginning. Then only a BFV-Restart will solve that issue.

In the other times the Radar can work multiple rounds without any problems. Maybe you find a bugfix for that issue.

![2019-06-10 14_14_30-Window](https://user-images.githubusercontent.com/51643624/59195983-bda70500-8b8d-11e9-818a-75415b8c6de4.png)

**Comment by 70RMUND** [comment]
Issue no longer found in newer versions of the script. Please re-open if you can reproduce.

Thanks!
